# Generated by Django 6.0.3 on 2026-03-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_tag_post_category_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_to",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
